import { setTimeout as sleep } from "node:timers/promises";
import { decode } from "@msgpack/msgpack";
import { Cli, z } from "incur";
import { getAuthenticatedContext } from "../../../auth.js";
import { commandGlobals, commandSignal } from "../../../command.js";
import { exists, fs } from "../../../fs.js";
import { handleError } from "../../../utils/errors.js";
import {
  type ExecutionEvent,
  executionEventSchema as executionStreamOutputSchema,
} from "../../../utils/execution-output.js";
import { fetch } from "../../../utils/http.js";
import {
  getExecutionLogs,
  getExecutionStepResults,
  type IntegrationFlow,
  isCniExecutionComplete,
  resolveFlow,
} from "../../../utils/integration/flows.js";
import { getPrismMetadata } from "../../../utils/integration/metadata.js";
import { getIntegrationSystemInstance } from "../../../utils/integration/query.js";
import { getAdaptivePollIntervalMs } from "../../../utils/polling.js";
import { getTriggerType } from "./listen.js";

type FormattedStepResult = {
  stepName: string;
  endedAt: string;
  result: Record<string, unknown>;
};

/** Payload format generated by the listen command for replay */
type ReplayablePayload = {
  flowId?: string;
  payload: unknown;
  contentType: string;
  headers: string | Record<string, string>;
  triggerType?: "WEBHOOK" | "POLLING";
};

const MISSING_ID_ERROR = "You must provide an integration ID.";
const TIMEOUT_SECONDS = 1200; // 20 minutes

/**
 * Zod schema for test command flags.
 * Validates command arguments and provides type-safe access to flag values.
 *
 * Complex validations handled:
 * - Tailing flags (cni-auto-end, result-file, jsonl) require tail-logs or tail-results
 * - Empty string validation for IDs/URLs
 * - Timeout must be a positive integer
 */
export const testFlagsSchema = z
  .object({
    "flow-id": z
      .string()
      .min(1)
      .optional()
      .describe("ID of the flow to test. Base64 encoded.")
      .meta({ cli: { char: "f", exclusive: ["flow-url", "flow-name"] } }),
    "flow-name": z
      .string()
      .min(1)
      .optional()
      .describe("Name of the flow to test.")
      .meta({ cli: { char: "n", exclusive: ["flow-url", "flow-id"] } }),
    "flow-url": z
      .string()
      .min(1)
      .optional()
      .describe("URL of the flow to test. Prefer to use flow-id instead, if possible.")
      .meta({ cli: { char: "u", exclusive: ["flow-id"] } }),
    "integration-id": z
      .string()
      .min(1)
      .optional()
      .describe("ID of the integration containing the flow to test. Base64 encoded.")
      .meta({ cli: { char: "i" } }),
    payload: z
      .string()
      .optional()
      .describe("Optional file containing a payload to run the flow with.")
      .meta({ cli: { char: "p" } }),
    "payload-content-type": z
      .string()
      .optional()
      .describe("Optional Content-Type for the test payload.")
      .meta({ cli: { char: "c", preserveExplicit: true, default: "application/json" } }),
    sync: z.boolean().optional().describe("Forces the flow to run synchronously."),
    "tail-results": z
      .boolean()
      .optional()
      .describe("Tail step results from the test execution until user interrupt or timeout."),
    "tail-logs": z
      .boolean()
      .optional()
      .describe("Tail logs from the test execution until user interrupt or timeout."),
    "cni-auto-end": z
      .boolean()
      .optional()
      .describe(
        "Automatically stop polling activity once an CNI flow execution completes. Some logs & results may not be returned this way. DOES NOT WORK FOR LOW-CODE FLOWS.",
      ),
    timeout: z.coerce
      .number()
      .int()
      .positive()
      .optional()
      .describe(
        "Optionally set a timeout (in seconds) to stop tail activity. Compatible with both low-code and CNI flows.",
      ),
    "result-file": z
      .string()
      .optional()
      .describe(
        "Optional file to append tailed execution result data to. Results are saved into JSON Lines.",
      )
      .meta({ cli: { char: "r" } }),
    jsonl: z
      .boolean()
      .optional()
      .describe("Optionally format the step and tail results output into JSON Lines."),
    debug: z.boolean().optional().describe("Enables debug mode on the test execution."),
    apiKey: z.string().optional().describe("Optional API key for flows with secured endpoints."),
  })
  .superRefine((data, ctx) => {
    const isTailing = data["tail-logs"] || data["tail-results"];

    // cni-auto-end only makes sense when tailing
    if (data["cni-auto-end"] && !isTailing) {
      ctx.addIssue({
        code: "custom",
        message: "--cni-auto-end requires --tail-logs or --tail-results",
        path: ["cni-auto-end"],
      });
    }

    // result-file only makes sense when tailing
    if (data["result-file"] && !isTailing) {
      ctx.addIssue({
        code: "custom",
        message: "--result-file requires --tail-logs or --tail-results",
        path: ["result-file"],
      });
    }

    // jsonl only makes sense when tailing
    if (data.jsonl && !isTailing) {
      ctx.addIssue({
        code: "custom",
        message: "--jsonl requires --tail-logs or --tail-results",
        path: ["jsonl"],
      });
    }
  });

export type TestFlags = z.infer<typeof testFlagsSchema>;

export const CONFIGURE_INSTANCE_PARAMS = {
  embed: "true",
  theme: "LIGHT",
  reconfigure: "true",
  screenConfiguration: JSON.stringify({
    configurationWizard: {
      mode: "streamlined",
    },
  }),
};

export default Cli.command({
  output: executionStreamOutputSchema,
  description: "Run a test execution of a flow",
  examples: [
    {
      description:
        "Test an integration flow with a payload file and tail the logs and step results:",
      options: {
        payload: "some_payload_file.xml",
        "payload-content-type": "application/xml",
        "tail-logs": true,
        "tail-results": true,
      },
    },
  ],
  options: testFlagsSchema,
  async *run(context): AsyncGenerator<ExecutionEvent> {
    const flags = { ...context.options, quiet: commandGlobals().quiet };
    const signal = commandSignal();

    const {
      sync,
      "flow-id": flowIdFlag,
      "flow-url": flowUrlFlag,
      "flow-name": flowNameFlag,
      "integration-id": integrationIdFlag,
      payload: payloadFilePath,
      "payload-content-type": contentType,
      "tail-logs": tailLogs,
      "tail-results": tailStepResults,
      "result-file": resultFilePath,
      timeout,
      debug,
      quiet,
      apiKey,
    } = flags;

    let triggerPayload = "";
    let payloadHeaders: Record<string, string> = {};
    let effectiveContentType = contentType ?? "application/json";
    let replayablePayload: ReplayablePayload | null = null;
    let autoEndPoll = flags["cni-auto-end"];

    if (payloadFilePath) {
      if (!(await exists(payloadFilePath))) {
        handleError({
          message: `No file found at ${payloadFilePath}. Please check the --trigger-payload-file (-p) parameter.`,
        });
      }

      const fileContent = await fs.readFile(payloadFilePath, { encoding: "utf-8" });
      replayablePayload = parseReplayablePayload(fileContent);

      if (replayablePayload) {
        // If the given payload file is from listening mode replay, we will parse it for
        // the body, content type, and headers, and merge that in with the given flags accordingly.
        triggerPayload =
          typeof replayablePayload.payload === "string"
            ? replayablePayload.payload
            : JSON.stringify(replayablePayload.payload);

        const hasExplicitContentType = contentType !== undefined;
        if (!hasExplicitContentType && replayablePayload.contentType) {
          effectiveContentType = replayablePayload.contentType;
        }

        if (typeof replayablePayload.headers === "string") {
          try {
            payloadHeaders = JSON.parse(replayablePayload.headers);
          } catch {
            throw new Error(
              `There was an error parsing the headers listed in the payload file: ${payloadFilePath}`,
            );
          }
        } else if (
          typeof replayablePayload.headers === "object" &&
          replayablePayload.headers !== null
        ) {
          payloadHeaders = replayablePayload.headers;
        }
      } else {
        // Not a replayable payload, use file content as-is (legacy behavior)
        triggerPayload = fileContent;

        // Validate JSON if that's what we're expecting
        if (contentType === "application/json") {
          try {
            JSON.parse(fileContent);
          } catch {
            handleError({
              message:
                "The provided trigger payload file contains malformed JSON. Please check the payload file (-p) and Content-Type (-c).",
            });
          }
        }
      }
    }

    let integrationId = integrationIdFlag;
    let invokeUrl = "";
    let selectedFlowId: string | undefined = flowIdFlag;
    let selectedFlow: IntegrationFlow | undefined;

    if (flowUrlFlag) {
      // flow-url provided - use it directly.
      invokeUrl = flowUrlFlag;
    } else {
      // Need integration ID to look up flow data
      if (!integrationId) {
        try {
          const metadata = await getPrismMetadata();
          integrationId = metadata.integrationId;

          if (!integrationId) {
            throw new Error();
          }
        } catch (_err) {
          handleError({
            message: MISSING_ID_ERROR,
          });
        }
      }

      const { isConfigured, isCodeNative, systemInstanceId } =
        await getIntegrationSystemInstance(integrationId);

      if (!systemInstanceId) {
        handleError({
          message:
            "No system instance was found for the given integration. Please re-import or contact support.",
        });
      }

      // Once we have an integration ID, we should validate that it's fully configured for testing.
      // Unfortunately can't do this in the direct invocation path b/c there's no reasonable way to
      // reverse-lookup integration ID from a webhook URL.
      if (!isConfigured) {
        const url = await configurationUrl(systemInstanceId);
        yield { type: "configuration-required", instanceId: systemInstanceId, url };
        yield { type: "completed", integrationId, status: "not-configured" };
        return;
      }

      if (!isCodeNative && autoEndPoll) {
        yield {
          type: "warning",
          message: "The integration is not code-native; --cni-auto-end is ignored.",
        };
        autoEndPoll = false;
      }

      selectedFlow = await resolveFlow({
        integrationId,
        flowId: selectedFlowId,
        flowName: flowNameFlag,
        promptMessage: "Select the flow to test:",
      });
      selectedFlowId = selectedFlow.id;
      invokeUrl = selectedFlow.testUrl;
    }

    const isPollingFromPayload = replayablePayload?.triggerType === "POLLING";
    const isPolling =
      isPollingFromPayload ||
      (selectedFlow ? getTriggerType(selectedFlow.trigger) === "POLLING" : false);

    if (flowUrlFlag && triggerPayload && !isPollingFromPayload) {
      // Warn when using flow-url with a non-replayable payload - we can't detect polling triggers w/o ID's
      yield {
        type: "warning",
        message:
          "Cannot detect polling triggers with --flow-url. For polling flows use a replayable payload or --flow-id.",
      };
    }

    if (!quiet) yield { type: "progress", message: "Starting execution" };

    // For polling flows with a payload, pass the payload via the simulated trigger result header
    let simulatedTriggerResult: string | undefined;
    if (isPolling && triggerPayload) {
      try {
        simulatedTriggerResult = JSON.stringify({
          payload: { body: { data: JSON.parse(triggerPayload) } },
        });
      } catch {
        simulatedTriggerResult = JSON.stringify({
          payload: { body: { data: triggerPayload } },
        });
      }
    }

    const response = await fetch(invokeUrl, {
      method: "POST",
      signal,
      body: isPolling ? undefined : triggerPayload,
      headers: {
        ...payloadHeaders,
        ...(debug ? { "prismatic-debug": "true" } : {}),
        ...(apiKey ? { "Api-Key": apiKey } : {}),
        ...(sync ? { "prismatic-synchronous": "true" } : {}),
        ...(simulatedTriggerResult
          ? { "prismatic-simulated-trigger-result": simulatedTriggerResult }
          : {}),
        ...(triggerPayload ? { "Content-Type": effectiveContentType } : {}),
      },
    });
    const responseData = z
      .object({ executionId: z.string().optional() })
      .passthrough()
      .parse(await response.json());
    const executionId =
      response.headers.get("prismatic-executionid") || responseData.executionId || "";
    yield {
      type: "execution",
      executionId,
      integrationId,
      flowId: selectedFlowId,
      response: responseData,
    };
    if (!(tailLogs || tailStepResults)) {
      yield { type: "completed", executionId, status: sync ? "completed" : "submitted" };
      return;
    }
    if (!executionId) throw new Error("The test response did not include an execution ID to tail");
    if (!quiet)
      yield {
        type: "warning",
        message: "Logs and step results may arrive out of chronological order.",
      };
    const startTime = Date.now();
    const deadline = startTime + (timeout ?? TIMEOUT_SECONDS) * 1000;
    let logCursor: string | undefined;
    let stepCursor: string | undefined;
    let completed = false;
    while (Date.now() < deadline) {
      await sleep(
        Math.min(getAdaptivePollIntervalMs(startTime), Math.max(0, deadline - Date.now())),
        undefined,
        { signal },
      );
      if (Date.now() >= deadline) break;
      if (tailLogs) {
        const result = await getExecutionLogs(executionId, logCursor);
        const edges = result.logs.edges;
        if (edges?.length) {
          logCursor = edges.at(-1)?.cursor;
          for (const edge of edges) {
            if (!edge?.node) continue;
            const log = edge.node;
            if (resultFilePath) await fs.appendFile(resultFilePath, `${JSON.stringify(log)}\n`);
            yield { type: "log", executionId, data: log };
          }
        }
      }
      if (tailStepResults) {
        const result = await fetchStepResultBatch(executionId, stepCursor, signal);
        stepCursor = result.cursor ?? stepCursor;
        for (const message of result.warnings) yield { type: "warning", message };
        for (const step of result.stepResults) {
          if (resultFilePath) await fs.appendFile(resultFilePath, `${JSON.stringify(step)}\n`);
          yield { type: "step-result", executionId, data: step };
        }
      }
      if (autoEndPoll && (await isCniExecutionComplete(executionId))) {
        completed = true;
        break;
      }
    }
    yield {
      type: "completed",
      executionId,
      status: completed ? "completed" : "timed-out",
      ...(resultFilePath ? { path: resultFilePath } : {}),
    };
  },
});

export async function fetchStepResultBatch(
  executionId: string,
  nextCursor?: string,
  signal?: AbortSignal,
) {
  const result = await getExecutionStepResults(executionId, nextCursor);
  const edges = result.executionResult?.stepResults.edges;
  const stepResults: FormattedStepResult[] = [];
  const warnings: string[] = [];
  for (const edge of edges ?? []) {
    if (!edge?.node) continue;
    const { endedAt, resultsUrl, stepName } = edge.node;
    try {
      const response = await fetch(resultsUrl, { signal });
      const result = decode(Buffer.from(await response.arrayBuffer())) as Record<string, unknown>;
      stepResults.push({ stepName: stepName ?? "unknown", endedAt: endedAt ?? "", result });
    } catch (error) {
      signal?.throwIfAborted();
      warnings.push(
        `Error fetching results for step ${stepName}: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }
  return { stepResults, warnings, cursor: edges?.at(-1)?.cursor };
}

function parseReplayablePayload(content: string): ReplayablePayload | null {
  try {
    const parsed = JSON.parse(content);
    if (
      typeof parsed === "object" &&
      parsed !== null &&
      "payload" in parsed &&
      "contentType" in parsed &&
      "headers" in parsed
    ) {
      return parsed as ReplayablePayload;
    }
    return null;
  } catch {
    return null;
  }
}

async function configurationUrl(systemInstanceId: string): Promise<string> {
  const { accessToken, url: endpoint } = await getAuthenticatedContext();
  const params = new URLSearchParams({
    ...CONFIGURE_INSTANCE_PARAMS,
    ...(accessToken && { jwt: accessToken }),
  });
  const url = new URL(`/configure-instance/${encodeURIComponent(systemInstanceId)}/`, endpoint);
  url.search = params.toString();
  return url.toString();
}

export type BuildFlagStringOptions = {
  payloadFilePath?: string;
  contentType?: string;
  tailLogs?: boolean;
  tailStepResults?: boolean;
  sync?: boolean;
  autoEndPoll?: boolean;
  resultFilePath?: string;
};

export const buildFlagString = (options: BuildFlagStringOptions): string => {
  const {
    payloadFilePath,
    contentType,
    tailLogs,
    tailStepResults,
    sync,
    autoEndPoll,
    resultFilePath,
  } = options;

  const flags: string[] = [];

  if (payloadFilePath) {
    flags.push(`-p=${payloadFilePath}`);
    flags.push(`-c=${contentType}`);
  }
  if (tailLogs) flags.push("--tail-logs");
  if (tailStepResults) flags.push("--tail-results");
  if (sync) flags.push("--sync");
  if (autoEndPoll) flags.push("--cni-auto-end");
  if (resultFilePath) flags.push(`-r=${resultFilePath}`);

  return flags.join(" ");
};
